version: '3'
services:
  mysql_db:
    image: mysql # docker pull mysql
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-work
  
  app: 
    depends_on:
      - mysql_db
    build: . # docker build . 
    container_name: cons-node
    ports:
      - 7070:8080
    networks:
      - node-work

      
volumes:
  mysql_db:
    driver: local
networks:
  node-work:
